//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeWork_15
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsOfBank
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<double> RateOfCredit { get; set; }
        public Nullable<double> MinRate { get; set; }
        public string FirstAccountValue { get; set; }
        public string SumOnFirstAccountValue { get; set; }
        public string SecondAccountValue { get; set; }
        public string SumOnSecondAccountValue { get; set; }
        public string DepositWithoutCapValue { get; set; }
        public string MonthDepositWithoutCapValue { get; set; }
        public string SumDepositWithoutCapValue { get; set; }
        public string DepositWithCapValue { get; set; }
        public string MonthDepositWithCapValue { get; set; }
        public string SumDepositWithCapValue { get; set; }
        public string CreditValue { get; set; }
        public string MonthCreditValue { get; set; }
        public string PecentOfCreditValue { get; set; }
        public Nullable<bool> isRedusedRate { get; set; }
        public string JournalOfClientActions { get; set; }
        public Nullable<bool> isCreatedDataDase { get; set; }
        public string FirstBaseMessages { get; set; }
        public string SecondBaseMessages { get; set; }
        public string ThirdBaseMessages { get; set; }
        public string FourtnBaseMessages { get; set; }
        public string FifthBaseMessages { get; set; }
        public string SixthBaseMessages { get; set; }
        public string SeventhBaseMessages { get; set; }
        public string EighthBaseMessages { get; set; }
        public string NinthBaseMessages { get; set; }
        public string TenthBaseMessages { get; set; }
        public Nullable<int> InitialMonthDepositWithCap { get; set; }
        public Nullable<int> InitialMonthCredit { get; set; }
        public Nullable<int> InitialSumCredit { get; set; }
    }
}
